sudo: false

language: go
go:
  - 1.4
  - 1.5

install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get -t -v ./...

script:
  - golint *.go
  - go fmt ./...
  - go vet ./...
  - go test -v ./...
  - gocov test | gocov report