sudo: false

language: go
go:
  - 1.4
  - 1.5

install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get -t -v ./...

before_script:
  - gofmt -l . >&2; exit 1 || exit 0
  - golint *.go
  - go vet ./...

script:
  - go test -v ./...
  - gocov test | gocov report